name: .NET Windows Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Debug List Files
        run: Get-ChildItem -Path ${{ github.workspace }} -Recurse
        shell: pwsh

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore Dependencies
        run: dotnet restore Quasar.sln

      - name: Build Solution
        run: dotnet build Quasar.sln --no-restore --configuration Release --output build_output

      - name: Zip Build Output
        run: Compress-Archive -Path build_output/* -DestinationPath build_output.zip

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build_output.zip
