name: .NET Framework Windows Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Debug List Files
        run: Get-ChildItem -Path ${{ github.workspace }} -Recurse
        shell: pwsh

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      - name: Restore Dependencies
        run: nuget restore Quasar.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build Solution
        run: msbuild Quasar.sln /p:Configuration=Release
        shell: cmd

      - name: Zip Build Output
        run: Compress-Archive -Path "D:\a\Quasar-Modded\Quasar-Modded\bin\Release\net452\*" -DestinationPath "build_output.zip"
        shell: pwsh

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build_output.zip
