name: .NET Windows Release

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Install Missing Dependencies
        run: |
          dotnet add package System.Resources.Extensions --version 7.0.0
          dotnet add package Microsoft.Build.Utilities.Core --version 17.9.2

      - name: Restore Dependencies
        run: dotnet restore --force

      - name: Build Solution
        run: dotnet build --no-restore --configuration Release --output build_output

      - name: Zip Build Output
        run: Compress-Archive -Path build_output/* -DestinationPath build_output.zip

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build_output.zip
